Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,11 +2,6 @@ name: Patch Samsung Health Monitor
 
 on:
   workflow_dispatch:
-    inputs:
-      apk_url:
-        description: 'Direct download URL of Stock SHM APK'
-        required: true
-        default: 'https://github.com/Dante-Bro/Samsung-Health-Monitor-MOD/releases/download/v1.2.5.003/Phone.Samsung.Health.Monitor.apk'
 
 jobs:
   patch:
@@ -32,9 +27,12 @@ jobs:
           wget -q https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar -O apktool.jar
           wget -q https://github.com/patrickfav/uber-apk-signer/releases/download/v1.3.0/uber-apk-signer-1.3.0.jar -O uber-apk-signer.jar
 
-      - name: Download Original APK
+      - name: Verify Original APK exists
         run: |
-          wget -O original.apk "${{ github.event.inputs.apk_url }}"
+          if [ ! -f "original.apk" ]; then
+            echo "ERROR: original.apk repository me nahi mila!"
+            exit 1
+          fi
 
       - name: Decompile APK
         run: |
@@ -55,5 +53,5 @@ jobs:
       - name: Upload Patched APK
         uses: actions/upload-artifact@v4
         with:
-          name: Patched-Samsung-Health-Monitor
+          name: My-Custom-Samsung-Health-Monitor
           path: output/*.apk
